export type BiomarkerCode = {
  name: string;
  category: string;
  unit: string | null;
  /** Abbreviated unit for compact row display; falls back to `unit` */
  shortUnit?: string;
  reference?: { low?: number; high?: number };
  /** % beyond range boundary before escalating status */
  threshold?: { borderline: number; abnormal: number };
};

export type Reading = {
  date: string;
  value: number | string;
  estimated?: boolean;
};

export const categories: Record<string, string> = {
  body: "body",
  performance: "performance",
  haematology: "haematology",
  biochemistry: "biochemistry",
  immunology: "immunology",
  hormones: "hormones",
  posture: "posture",
  circumferences: "circumferences",
};

export const codes: Record<string, BiomarkerCode> = {
  // --- body ---
  age: { name: "Age", category: "body", unit: "years" },
  fitness_age: { name: "Fitness Age (Garmin)", category: "body", unit: "years" },
  height: { name: "Height", category: "body", unit: "cm" },
  weight: { name: "Weight", category: "body", unit: "kg" },
  body_fat_pct: { name: "Body Fat", category: "body", unit: "%", reference: { low: 8, high: 19 }, threshold: { borderline: 10, abnormal: 25 } },
  fat_mass: { name: "Fat Mass", category: "body", unit: "kg", reference: { low: 8.4, high: 16.9 }, threshold: { borderline: 10, abnormal: 25 } },
  smm: { name: "Skeletal Muscle Mass", category: "body", unit: "kg", reference: { low: 30.3, high: 37.6 }, threshold: { borderline: 10, abnormal: 25 } },
  lean_body_mass: { name: "Lean Body Mass", category: "body", unit: "kg", reference: { low: 53.9, high: 65.9 }, threshold: { borderline: 10, abnormal: 25 } },
  muscle_mass: { name: "Muscle Mass", category: "body", unit: "kg", reference: { low: 50.8, high: 62.2 }, threshold: { borderline: 10, abnormal: 25 } },
  body_water: { name: "Body Water", category: "body", unit: "kg", reference: { low: 39.7, high: 48.5 }, threshold: { borderline: 10, abnormal: 25 } },
  whr: { name: "Waist-Hip Ratio", category: "body", unit: null, reference: { low: 0.80, high: 0.90 }, threshold: { borderline: 10, abnormal: 25 } },
  bmr: { name: "Basal Metabolic Rate", category: "body", unit: "kcal/d", reference: { low: 1497.7, high: 1830.5 }, threshold: { borderline: 10, abnormal: 25 } },
  visceral_fat: { name: "Visceral Fat Level", category: "body", unit: null, reference: { low: 1.0, high: 10.0 }, threshold: { borderline: 10, abnormal: 25 } },

  // --- circumferences ---
  neck_circumference: { name: "Neck Circumference", category: "circumferences", unit: "cm" },
  upper_arm_l: { name: "Upper Arm (L)", category: "circumferences", unit: "cm" },
  upper_arm_r: { name: "Upper Arm (R)", category: "circumferences", unit: "cm" },
  chest_circumference: { name: "Chest Circumference", category: "circumferences", unit: "cm" },
  waist_high: { name: "High Waist", category: "circumferences", unit: "cm" },
  waist_mid: { name: "Mid Waist", category: "circumferences", unit: "cm" },
  waist_low: { name: "Low Waist", category: "circumferences", unit: "cm" },
  hip_circumference: { name: "Hip Circumference", category: "circumferences", unit: "cm" },
  thigh_l: { name: "Thigh (L)", category: "circumferences", unit: "cm" },
  thigh_l_min: { name: "Min Thigh (L)", category: "circumferences", unit: "cm" },
  thigh_r: { name: "Thigh (R)", category: "circumferences", unit: "cm" },
  thigh_r_min: { name: "Min Thigh (R)", category: "circumferences", unit: "cm" },
  calf_l: { name: "Calf (L)", category: "circumferences", unit: "cm" },
  calf_r: { name: "Calf (R)", category: "circumferences", unit: "cm" },

  // --- haematology ---
  hb: { name: "Haemoglobin", category: "haematology", unit: "g/dL", reference: { low: 13.5, high: 17.5 }, threshold: { borderline: 7, abnormal: 15 } },
  hct: { name: "Haematocrit", category: "haematology", unit: "%", reference: { low: 40, high: 52 }, threshold: { borderline: 7, abnormal: 15 } },
  rbc: { name: "Red Blood Cell", category: "haematology", unit: "x10\u2076/mm\u00b3", reference: { low: 4.4, high: 5.9 }, threshold: { borderline: 7, abnormal: 15 } },
  rdw: { name: "RDW", category: "haematology", unit: "%", reference: { low: 11.5, high: 14.5 }, threshold: { borderline: 10, abnormal: 20 } },
  mcv: { name: "MCV", category: "haematology", unit: "fL", reference: { low: 80, high: 100 }, threshold: { borderline: 5, abnormal: 15 } },
  mch: { name: "MCH", category: "haematology", unit: "pg", reference: { low: 27, high: 33 }, threshold: { borderline: 7, abnormal: 15 } },
  mchc: { name: "MCHC", category: "haematology", unit: "g/dL", reference: { low: 32, high: 36 }, threshold: { borderline: 5, abnormal: 10 } },
  wbc: { name: "Total WBC", category: "haematology", unit: "x10\u00b3/mm\u00b3", reference: { low: 4.5, high: 11.0 }, threshold: { borderline: 10, abnormal: 25 } },
  eosinophils_pct: { name: "Eosinophils %", category: "haematology", unit: "%", reference: { low: 1, high: 4 }, threshold: { borderline: 25, abnormal: 50 } },
  eosinophils: { name: "Eosinophils", category: "haematology", unit: "/mm\u00b3", reference: { low: 100, high: 500 }, threshold: { borderline: 25, abnormal: 50 } },
  neutrophils_pct: { name: "Neutrophils %", category: "haematology", unit: "%", reference: { low: 40, high: 70 }, threshold: { borderline: 10, abnormal: 25 } },
  neutrophils: { name: "Neutrophils", category: "haematology", unit: "/mm\u00b3", reference: { low: 1800, high: 7700 }, threshold: { borderline: 10, abnormal: 25 } },
  lymphocytes_pct: { name: "Lymphocytes %", category: "haematology", unit: "%", reference: { low: 20, high: 40 }, threshold: { borderline: 10, abnormal: 25 } },
  lymphocytes: { name: "Lymphocytes", category: "haematology", unit: "/mm\u00b3", reference: { low: 1000, high: 4800 }, threshold: { borderline: 10, abnormal: 25 } },
  monocytes_pct: { name: "Monocytes %", category: "haematology", unit: "%", reference: { low: 2, high: 8 }, threshold: { borderline: 15, abnormal: 30 } },
  monocytes: { name: "Monocytes", category: "haematology", unit: "/mm\u00b3", reference: { low: 200, high: 800 }, threshold: { borderline: 15, abnormal: 30 } },
  basophils_pct: { name: "Basophils %", category: "haematology", unit: "%", reference: { low: 0, high: 1 }, threshold: { borderline: 25, abnormal: 50 } },
  basophils: { name: "Basophils", category: "haematology", unit: "/mm\u00b3", reference: { low: 0, high: 200 }, threshold: { borderline: 25, abnormal: 50 } },
  platelets: { name: "Platelet Count", category: "haematology", unit: "x10\u00b3/mm\u00b3", reference: { low: 150, high: 400 }, threshold: { borderline: 10, abnormal: 25 } },
  mpv: { name: "MPV", category: "haematology", unit: "fL", reference: { low: 7.5, high: 11.5 }, threshold: { borderline: 10, abnormal: 20 } },
  esr: { name: "ESR", category: "haematology", unit: "mm/hr", reference: { low: 0, high: 15 }, threshold: { borderline: 10, abnormal: 30 } },

  // --- biochemistry ---
  glucose_fasting: { name: "Glucose (Fasting)", category: "biochemistry", unit: "mg/dL", reference: { low: 70, high: 100 }, threshold: { borderline: 3, abnormal: 10 } },
  hba1c: { name: "Haemoglobin A1C", category: "biochemistry", unit: "%", reference: { high: 5.7 }, threshold: { borderline: 3, abnormal: 8 } },
  cholesterol_total: { name: "Cholesterol (Total)", category: "biochemistry", unit: "mg/dL", reference: { high: 200 }, threshold: { borderline: 5, abnormal: 20 } },
  hdl: { name: "HDL Cholesterol", category: "biochemistry", unit: "mg/dL", reference: { low: 40 }, threshold: { borderline: 10, abnormal: 25 } },
  ldl: { name: "LDL Cholesterol (Direct)", category: "biochemistry", unit: "mg/dL", reference: { high: 130 }, threshold: { borderline: 8, abnormal: 20 } },
  triglycerides: { name: "Triglyceride", category: "biochemistry", unit: "mg/dL", reference: { high: 150 }, threshold: { borderline: 10, abnormal: 30 } },
  bun: { name: "BUN", category: "biochemistry", unit: "mg/dL", reference: { low: 7, high: 20 }, threshold: { borderline: 10, abnormal: 25 } },
  creatinine: { name: "Creatinine", category: "biochemistry", unit: "mg/dL", reference: { low: 0.7, high: 1.3 }, threshold: { borderline: 5, abnormal: 15 } },
  egfr: { name: "eGFR", category: "biochemistry", unit: "mL/min/1.73m\u00b2", shortUnit: "ml/min", reference: { low: 60 }, threshold: { borderline: 10, abnormal: 25 } },
  uric_acid: { name: "Uric Acid", category: "biochemistry", unit: "mg/dL", reference: { low: 3.5, high: 7.2 }, threshold: { borderline: 7, abnormal: 20 } },
  alt: { name: "ALT (SGPT)", category: "biochemistry", unit: "U/L", reference: { low: 7, high: 56 }, threshold: { borderline: 10, abnormal: 50 } },
  ast: { name: "AST (SGOT)", category: "biochemistry", unit: "U/L", reference: { low: 10, high: 40 }, threshold: { borderline: 10, abnormal: 50 } },
  ggt: { name: "GGT", category: "biochemistry", unit: "U/L", reference: { low: 9, high: 48 }, threshold: { borderline: 10, abnormal: 50 } },
  alp: { name: "ALP", category: "biochemistry", unit: "U/L", reference: { low: 44, high: 147 }, threshold: { borderline: 10, abnormal: 25 } },
  total_protein: { name: "Total Protein", category: "biochemistry", unit: "g/dL", reference: { low: 6.0, high: 8.3 }, threshold: { borderline: 5, abnormal: 15 } },
  bilirubin_total: { name: "Bilirubin (Total)", category: "biochemistry", unit: "mg/dL", reference: { low: 0.1, high: 1.2 }, threshold: { borderline: 10, abnormal: 30 } },
  bilirubin_direct: { name: "Bilirubin (Direct)", category: "biochemistry", unit: "mg/dL", reference: { high: 0.3 }, threshold: { borderline: 10, abnormal: 30 } },
  albumin: { name: "Albumin", category: "biochemistry", unit: "g/dL", reference: { low: 3.5, high: 5.5 }, threshold: { borderline: 5, abnormal: 15 } },
  globulin: { name: "Globulin", category: "biochemistry", unit: "g/dL", reference: { low: 2.0, high: 3.5 }, threshold: { borderline: 10, abnormal: 25 } },
  ag_ratio: { name: "A/G Ratio", category: "biochemistry", unit: null, reference: { low: 1.1, high: 2.5 }, threshold: { borderline: 10, abnormal: 25 } },

  ferritin: { name: "Ferritin", category: "biochemistry", unit: "ng/mL", reference: { low: 30, high: 400 }, threshold: { borderline: 10, abnormal: 25 } },

  // --- immunology ---
  tsh: { name: "TSH", category: "immunology", unit: "mU/L", reference: { low: 0.350, high: 4.940 }, threshold: { borderline: 5, abnormal: 20 } },
  psa: { name: "PSA", category: "immunology", unit: "ng/mL", reference: { high: 4.0 }, threshold: { borderline: 10, abnormal: 25 } },
  cea: { name: "CEA", category: "immunology", unit: "ng/mL", reference: { high: 5.0 }, threshold: { borderline: 10, abnormal: 50 } },
  afp: { name: "AFP", category: "immunology", unit: "ng/mL", reference: { high: 8.3 }, threshold: { borderline: 15, abnormal: 50 } },

  // --- hormones ---
  testosterone: { name: "Testosterone", category: "hormones", unit: "ng/dL", reference: { low: 300, high: 1000 }, threshold: { borderline: 10, abnormal: 25 } },
  free_testosterone: { name: "Free Testosterone", category: "hormones", unit: "pmol/L", reference: { low: 160, high: 777 }, threshold: { borderline: 10, abnormal: 25 } },
  shbg: { name: "SHBG", category: "hormones", unit: "nmol/L", reference: { low: 10, high: 57 }, threshold: { borderline: 10, abnormal: 25 } },
  estradiol: { name: "Estradiol", category: "hormones", unit: "pmol/L", reference: { low: 40, high: 161 }, threshold: { borderline: 15, abnormal: 30 } },
  lh: { name: "LH", category: "hormones", unit: "IU/L", reference: { low: 0.57, high: 12.07 }, threshold: { borderline: 10, abnormal: 25 } },
  fsh: { name: "FSH", category: "hormones", unit: "IU/L", reference: { low: 0.95, high: 11.95 }, threshold: { borderline: 10, abnormal: 25 } },
  prolactin: { name: "Prolactin", category: "hormones", unit: "mU/L", reference: { low: 73.4, high: 411 }, threshold: { borderline: 10, abnormal: 30 } },
  free_t3: { name: "Free T3", category: "hormones", unit: "pmol/L", reference: { low: 2.63, high: 5.7 }, threshold: { borderline: 7, abnormal: 20 } },
  free_t4: { name: "Free T4", category: "hormones", unit: "pmol/L", reference: { low: 9.01, high: 19.0 }, threshold: { borderline: 7, abnormal: 20 } },

  // Posture ranges are intentionally more lenient than a strict "ideal" neutral
  // alignment so moderate deviations read as amber and the clearest outlier stays red.
  forward_head: { name: "Forward Head Posture", category: "posture", unit: "cm", reference: { high: 4.0 }, threshold: { borderline: 15, abnormal: 120 } },
  head_tilt: { name: "Head Tilt", category: "posture", unit: "°", reference: { low: -2.5, high: 2.5 }, threshold: { borderline: 3, abnormal: 15 } },
  rounded_shoulder_l: { name: "Rounded Shoulder (L)", category: "posture", unit: "cm", reference: { high: 5.0 }, threshold: { borderline: 15, abnormal: 120 } },
  rounded_shoulder_r: { name: "Rounded Shoulder (R)", category: "posture", unit: "cm", reference: { high: 5.0 }, threshold: { borderline: 15, abnormal: 120 } },
  uneven_shoulders: { name: "Uneven Shoulders", category: "posture", unit: "°", reference: { low: -3.0, high: 3.0 }, threshold: { borderline: 10, abnormal: 50 } },
  anterior_pelvic_shift: { name: "Anterior Pelvic Shift", category: "posture", unit: "cm", reference: { low: -4.0, high: 4.0 }, threshold: { borderline: 15, abnormal: 80 } },
  knee_hyperext_l: { name: "Left Knee Angle", category: "posture", unit: "°", reference: { high: 180 }, threshold: { borderline: 1, abnormal: 3 } },
  knee_hyperext_r: { name: "Right Knee Angle", category: "posture", unit: "°", reference: { high: 180 }, threshold: { borderline: 1, abnormal: 3 } },

  // --- performance ---
  rhr: { name: "Resting Heart Rate", category: "performance", unit: "bpm", reference: { low: 40, high: 70 }, threshold: { borderline: 10, abnormal: 25 } },
  hrv: { name: "HRV", category: "performance", unit: "ms", reference: { low: 30, high: 50 }, threshold: { borderline: 15, abnormal: 30 } },
  vo2max: { name: "VO2 Max", category: "performance", unit: "mL/kg/min", shortUnit: "ml/kg", reference: { low: 40, high: 60 }, threshold: { borderline: 10, abnormal: 25 } },
  pr_marathon: { name: "Marathon PR", category: "performance", unit: null },
  pr_half_marathon: { name: "Half Marathon PR", category: "performance", unit: null },
  pr_10k: { name: "10K PR", category: "performance", unit: null },
  pr_deadlift: { name: "Deadlift 1RM", category: "performance", unit: "kg" },
  pr_squat: { name: "Squat 1RM", category: "performance", unit: "kg" },
  pr_bench: { name: "Bench Press 1RM", category: "performance", unit: "kg" },
};

/** Each marker has its own array of readings, independent of any checkup */
export const BIRTH_DATE = new Date(1994, 0, 11);

export const readings: Record<string, Reading[]> = {
  fitness_age: [{ date: "2026-04-03", value: 27 }],
  height: [{ date: "2024-08-14", value: 179 }],
  weight: [{ date: "2024-08-14", value: 68.5 }, { date: "2025-07-29", value: 68.5 }, { date: "2026-04-03", value: 72, estimated: true }, { date: "2026-04-08", value: 71.8 }],
  body_fat_pct: [{ date: "2025-07-29", value: 12.1 }, { date: "2026-04-03", value: 14, estimated: true }, { date: "2026-04-08", value: 13.4 }],
  fat_mass: [{ date: "2025-07-29", value: 8.3 }, { date: "2026-04-08", value: 9.7 }],
  smm: [{ date: "2026-04-08", value: 35.7 }],
  lean_body_mass: [{ date: "2026-04-08", value: 62.1 }],
  muscle_mass: [{ date: "2026-04-08", value: 59.1 }],
  body_water: [{ date: "2026-04-08", value: 45.4 }],
  whr: [{ date: "2026-04-08", value: 0.85 }],
  bmr: [{ date: "2026-04-08", value: 1724.7 }],
  visceral_fat: [{ date: "2026-04-08", value: 3.0 }],
  neck_circumference: [{ date: "2026-04-08", value: 35.3 }],
  upper_arm_l: [{ date: "2026-04-08", value: 29.5 }],
  upper_arm_r: [{ date: "2026-04-08", value: 29.5 }],
  chest_circumference: [{ date: "2026-04-08", value: 98.0 }],
  waist_high: [{ date: "2026-04-08", value: 79.2 }],
  waist_mid: [{ date: "2026-04-08", value: 86.1 }],
  waist_low: [{ date: "2026-04-08", value: 90.2 }],
  hip_circumference: [{ date: "2026-04-08", value: 104.4 }],
  thigh_l: [{ date: "2026-04-08", value: 72.4 }],
  thigh_l_min: [{ date: "2026-04-08", value: 39.6 }],
  thigh_r: [{ date: "2026-04-08", value: 71.4 }],
  thigh_r_min: [{ date: "2026-04-08", value: 39.1 }],
  calf_l: [{ date: "2026-04-08", value: 35.1 }],
  calf_r: [{ date: "2026-04-08", value: 34.0 }],
  hb: [{ date: "2024-08-14", value: 16.3 }, { date: "2026-04-03", value: 17.7 }],
  hct: [{ date: "2024-08-14", value: 46.1 }, { date: "2026-04-03", value: 50.7 }],
  rbc: [{ date: "2024-08-14", value: 5.32 }, { date: "2026-04-03", value: 5.83 }],
  rdw: [{ date: "2024-08-14", value: 11.2 }, { date: "2026-04-03", value: 11.4 }],
  mcv: [{ date: "2024-08-14", value: 86.7 }, { date: "2026-04-03", value: 87.0 }],
  mch: [{ date: "2024-08-14", value: 30.6 }, { date: "2026-04-03", value: 30.4 }],
  mchc: [{ date: "2024-08-14", value: 35.4 }, { date: "2026-04-03", value: 34.9 }],
  wbc: [{ date: "2024-08-14", value: 5.54 }, { date: "2026-04-03", value: 5.3 }],
  eosinophils_pct: [{ date: "2024-08-14", value: 2.7 }, { date: "2026-04-03", value: 3.6 }],
  eosinophils: [{ date: "2024-08-14", value: 150 }, { date: "2026-04-03", value: 190 }],
  neutrophils_pct: [{ date: "2024-08-14", value: 65.1 }, { date: "2026-04-03", value: 60.5 }],
  neutrophils: [{ date: "2024-08-14", value: 3607 }, { date: "2026-04-03", value: 3230 }],
  lymphocytes_pct: [{ date: "2024-08-14", value: 26.5 }, { date: "2026-04-03", value: 26.1 }],
  lymphocytes: [{ date: "2024-08-14", value: 1468 }, { date: "2026-04-03", value: 1390 }],
  monocytes_pct: [{ date: "2024-08-14", value: 5.2 }, { date: "2026-04-03", value: 9.0 }],
  monocytes: [{ date: "2024-08-14", value: 288 }, { date: "2026-04-03", value: 480 }],
  basophils_pct: [{ date: "2024-08-14", value: 0.5 }, { date: "2026-04-03", value: 0.8 }],
  basophils: [{ date: "2024-08-14", value: 28 }, { date: "2026-04-03", value: 40 }],
  platelets: [{ date: "2024-08-14", value: 230 }, { date: "2026-04-03", value: 247 }],
  mpv: [{ date: "2024-08-14", value: 10 }],
  glucose_fasting: [{ date: "2024-08-14", value: 99 }],
  hba1c: [{ date: "2024-08-14", value: 4.9 }, { date: "2026-04-03", value: 5.3 }],
  cholesterol_total: [{ date: "2024-08-14", value: 212 }],
  hdl: [{ date: "2024-08-14", value: 59 }],
  ldl: [{ date: "2024-08-14", value: 135 }],
  triglycerides: [{ date: "2024-08-14", value: 47 }],
  bun: [{ date: "2024-08-14", value: 14.4 }],
  creatinine: [{ date: "2024-08-14", value: 1.0 }],
  egfr: [{ date: "2024-08-14", value: 100.6 }],
  uric_acid: [{ date: "2024-08-14", value: 6.6 }],
  alt: [{ date: "2024-08-14", value: 14 }],
  ast: [{ date: "2024-08-14", value: 20 }],
  ggt: [{ date: "2024-08-14", value: 17 }],
  alp: [{ date: "2024-08-14", value: 81 }],
  total_protein: [{ date: "2024-08-14", value: 6.93 }],
  bilirubin_total: [{ date: "2024-08-14", value: 0.8 }],
  bilirubin_direct: [{ date: "2024-08-14", value: 0.3 }],
  albumin: [{ date: "2024-08-14", value: 4.85 }, { date: "2026-04-03", value: 4.7 }],
  globulin: [{ date: "2024-08-14", value: 2.08 }],
  ag_ratio: [{ date: "2024-08-14", value: 2.33 }],
  tsh: [{ date: "2024-08-14", value: 0.812 }, { date: "2026-04-03", value: 1.14 }],
  psa: [{ date: "2024-08-14", value: 0.148 }],
  cea: [{ date: "2024-08-14", value: 3.05 }],
  afp: [{ date: "2024-08-14", value: 0.45 }],
  testosterone: [{ date: "2024-08-14", value: 880 }],
  free_testosterone: [{ date: "2026-04-03", value: 270.31 }],
  shbg: [{ date: "2026-04-03", value: 41.7 }],
  estradiol: [{ date: "2026-04-03", value: 36 }],
  lh: [{ date: "2026-04-03", value: 3.16 }],
  fsh: [{ date: "2026-04-03", value: 5.63 }],
  prolactin: [{ date: "2026-04-03", value: 432.69 }],
  free_t3: [{ date: "2026-04-03", value: 4.24 }],
  free_t4: [{ date: "2026-04-03", value: 14.29 }],
  ferritin: [{ date: "2026-04-03", value: 155.3 }],
  esr: [{ date: "2026-04-03", value: 6 }],
  forward_head: [{ date: "2026-04-08", value: 8.1 }],
  head_tilt: [{ date: "2026-04-08", value: 2.6 }],
  rounded_shoulder_l: [{ date: "2026-04-08", value: 9.9 }],
  rounded_shoulder_r: [{ date: "2026-04-08", value: 7.9 }],
  uneven_shoulders: [{ date: "2026-04-08", value: -4.3 }],
  anterior_pelvic_shift: [{ date: "2026-04-08", value: 11.2 }],
  knee_hyperext_l: [{ date: "2026-04-08", value: 184.3 }],
  knee_hyperext_r: [{ date: "2026-04-08", value: 184.0 }],
  rhr: [{ date: "2026-04-03", value: 57 }],
  hrv: [{ date: "2026-04-03", value: 41 }],
  vo2max: [{ date: "2025-01-01", value: 48, estimated: true }, { date: "2025-07-29", value: 60.2 }, { date: "2026-04-03", value: 52, estimated: true }],
  pr_marathon: [{ date: "2025-12-07", value: "3:11:17" }],
  pr_half_marathon: [{ date: "2022-09-03", value: "1:32:03" }],
  pr_10k: [{ date: "2025-11-11", value: "39:29" }],
  pr_deadlift: [{ date: "2025-07-29", value: 116, estimated: true }],
  pr_squat: [{ date: "2025-07-29", value: 80, estimated: true }],
  pr_bench: [{ date: "2025-07-29", value: 58, estimated: true }],
};
